using System.Collections.Generic;
using System.Linq;

namespace Com.ByteAnalysis.IFacilita.SearchProtest.Service.Mapper
{
    public class EnumMapperJudicialDistrict
    {
        List<EnumParse> list = new List<EnumParse>();
        public EnumMapperJudicialDistrict()
        {
            list = new List<EnumParse>();
            list.Add(new EnumParse { Code = 3550308, Description = "SAO PAULO" });
            list.Add(new EnumParse { Code = 3500105, Description = "ADAMANTINA" });
            list.Add(new EnumParse { Code = 3500303, Description = "AGUAI" });
            list.Add(new EnumParse { Code = 3500501, Description = "AGUAS DE LINDOIA" });
            list.Add(new EnumParse { Code = 3500709, Description = "AGUDOS" });
            list.Add(new EnumParse { Code = 3501004, Description = "ALTINOPOLIS" });
            list.Add(new EnumParse { Code = 3501608, Description = "AMERICANA" });
            list.Add(new EnumParse { Code = 3501905, Description = "AMPARO" });
            list.Add(new EnumParse { Code = 3502101, Description = "ANDRADINA" });
            list.Add(new EnumParse { Code = 3502200, Description = "ANGATUBA" });
            list.Add(new EnumParse { Code = 3502507, Description = "APARECIDA" });
            list.Add(new EnumParse { Code = 3502705, Description = "APIAI" });
            list.Add(new EnumParse { Code = 3502804, Description = "ARACATUBA" });
            list.Add(new EnumParse { Code = 3503208, Description = "ARARAQUARA" });
            list.Add(new EnumParse { Code = 3503307, Description = "ARARAS" });
            list.Add(new EnumParse { Code = 3504008, Description = "ASSIS" });
            list.Add(new EnumParse { Code = 3504107, Description = "ATIBAIA" });
            list.Add(new EnumParse { Code = 3504206, Description = "AURIFLAMA" });
            list.Add(new EnumParse { Code = 3504503, Description = "AVARE" });
            list.Add(new EnumParse { Code = 3504909, Description = "BANANAL" });
            list.Add(new EnumParse { Code = 3505203, Description = "BARIRI" });
            list.Add(new EnumParse { Code = 3505302, Description = "BARRA BONITA" });
            list.Add(new EnumParse { Code = 3505500, Description = "BARRETOS" });
            list.Add(new EnumParse { Code = 3505708, Description = "BARUERI" });
            list.Add(new EnumParse { Code = 3505906, Description = "BATATAIS" });
            list.Add(new EnumParse { Code = 3506003, Description = "BAURU" });
            list.Add(new EnumParse { Code = 3506102, Description = "BEBEDOURO" });
            list.Add(new EnumParse { Code = 3506409, Description = "BILAC" });
            list.Add(new EnumParse { Code = 3506508, Description = "BIRIGUI" });
            list.Add(new EnumParse { Code = 3507001, Description = "BOITUVA" });
            list.Add(new EnumParse { Code = 3507407, Description = "BORBOREMA" });
            list.Add(new EnumParse { Code = 3507506, Description = "BOTUCATU" });
            list.Add(new EnumParse { Code = 3507605, Description = "BRAGANCA PAULISTA" });
            list.Add(new EnumParse { Code = 3507803, Description = "BRODOWSKI" });
            list.Add(new EnumParse { Code = 3507902, Description = "BROTAS" });
            list.Add(new EnumParse { Code = 3508108, Description = "BURITAMA" });
            list.Add(new EnumParse { Code = 3508405, Description = "CABREUVA" });
            list.Add(new EnumParse { Code = 3508504, Description = "CACAPAVA" });
            list.Add(new EnumParse { Code = 3508603, Description = "CACHOEIRA PAULISTA" });
            list.Add(new EnumParse { Code = 3508702, Description = "CACONDE" });
            list.Add(new EnumParse { Code = 3508801, Description = "CAFELANDIA" });
            list.Add(new EnumParse { Code = 3509403, Description = "CAJURU" });
            list.Add(new EnumParse { Code = 3509502, Description = "CAMPINAS" });
            list.Add(new EnumParse { Code = 3509700, Description = "CAMPOS DO JORDAO" });
            list.Add(new EnumParse { Code = 3509908, Description = "CANANEIA" });
            list.Add(new EnumParse { Code = 3510005, Description = "CANDIDO MOTA" });
            list.Add(new EnumParse { Code = 3510203, Description = "CAPAO BONITO" });
            list.Add(new EnumParse { Code = 3510401, Description = "CAPIVARI" });
            list.Add(new EnumParse { Code = 3510500, Description = "CARAGUATATUBA" });
            list.Add(new EnumParse { Code = 3510609, Description = "CARAPICUIBA" });
            list.Add(new EnumParse { Code = 3510708, Description = "CARDOSO" });
            list.Add(new EnumParse { Code = 3510807, Description = "CASA BRANCA" });
            list.Add(new EnumParse { Code = 3511102, Description = "CATANDUVA" });
            list.Add(new EnumParse { Code = 3511409, Description = "CERQUEIRA CESAR" });
            list.Add(new EnumParse { Code = 3511508, Description = "CERQUILHO" });
            list.Add(new EnumParse { Code = 3557204, Description = "CHAVANTES" });
            list.Add(new EnumParse { Code = 3512001, Description = "COLINA" });
            list.Add(new EnumParse { Code = 3512308, Description = "CONCHAS" });
            list.Add(new EnumParse { Code = 3512407, Description = "CORDEIROPOLIS" });
            list.Add(new EnumParse { Code = 3512803, Description = "COSMOPOLIS" });
            list.Add(new EnumParse { Code = 3513009, Description = "COTIA" });
            list.Add(new EnumParse { Code = 3513108, Description = "CRAVINHOS" });
            list.Add(new EnumParse { Code = 3513405, Description = "CRUZEIRO" });
            list.Add(new EnumParse { Code = 3513504, Description = "CUBATAO" });
            list.Add(new EnumParse { Code = 3513603, Description = "CUNHA" });
            list.Add(new EnumParse { Code = 3513702, Description = "DESCALVADO" });
            list.Add(new EnumParse { Code = 3513801, Description = "DIADEMA" });
            list.Add(new EnumParse { Code = 3514106, Description = "DOIS CORREGOS" });
            list.Add(new EnumParse { Code = 3514403, Description = "DRACENA" });
            list.Add(new EnumParse { Code = 3514502, Description = "DUARTINA" });
            list.Add(new EnumParse { Code = 3514809, Description = "ELDORADO" });
            list.Add(new EnumParse { Code = 3515004, Description = "EMBU" });
            list.Add(new EnumParse { Code = 3515186, Description = "ESPIRITO SANTO DO PINHAL" });
            list.Add(new EnumParse { Code = 3515202, Description = "ESTRELA D OESTE" });
            list.Add(new EnumParse { Code = 3515400, Description = "FARTURA" });
            list.Add(new EnumParse { Code = 3515509, Description = "FERNANDOPOLIS" });
            list.Add(new EnumParse { Code = 3516200, Description = "FRANCA" });
            list.Add(new EnumParse { Code = 3516309, Description = "FRANCISCO MORATO" });
            list.Add(new EnumParse { Code = 3516408, Description = "FRANCO DA ROCHA" });
            list.Add(new EnumParse { Code = 3516606, Description = "GALIA" });
            list.Add(new EnumParse { Code = 3516705, Description = "GARCA" });
            list.Add(new EnumParse { Code = 3516903, Description = "GENERAL SALGADO" });
            list.Add(new EnumParse { Code = 3532800, Description = "GETULINA" });
            list.Add(new EnumParse { Code = 3517406, Description = "GUAIRA" });
            list.Add(new EnumParse { Code = 3517703, Description = "GUARA" });
            list.Add(new EnumParse { Code = 3518206, Description = "GUARARAPES" });
            list.Add(new EnumParse { Code = 3518404, Description = "GUARATINGUETA" });
            list.Add(new EnumParse { Code = 3518602, Description = "GUARIBA" });
            list.Add(new EnumParse { Code = 3518701, Description = "GUARUJA" });
            list.Add(new EnumParse { Code = 3518800, Description = "GUARULHOS" });
            list.Add(new EnumParse { Code = 3519600, Description = "IBITINGA" });
            list.Add(new EnumParse { Code = 3519709, Description = "IBIUNA" });
            list.Add(new EnumParse { Code = 3520103, Description = "IGARAPAVA" });
            list.Add(new EnumParse { Code = 3520301, Description = "IGUAPE" });
            list.Add(new EnumParse { Code = 3520442, Description = "ILHA SOLTEIRA" });
            list.Add(new EnumParse { Code = 3520509, Description = "INDAIATUBA" });
            list.Add(new EnumParse { Code = 3520905, Description = "IPAUSSU" });
            list.Add(new EnumParse { Code = 3521309, Description = "IPUA" });
            list.Add(new EnumParse { Code = 3521804, Description = "ITAI" });
            list.Add(new EnumParse { Code = 3522109, Description = "ITANHAEM" });
            list.Add(new EnumParse { Code = 3522208, Description = "ITAPECERICA DA SERRA" });
            list.Add(new EnumParse { Code = 3522307, Description = "ITAPETININGA" });
            list.Add(new EnumParse { Code = 3522406, Description = "ITAPEVA" });
            list.Add(new EnumParse { Code = 3522505, Description = "ITAPEVI" });
            list.Add(new EnumParse { Code = 3522604, Description = "ITAPIRA" });
            list.Add(new EnumParse { Code = 3522703, Description = "ITAPOLIS" });
            list.Add(new EnumParse { Code = 3522802, Description = "ITAPORANGA" });
            list.Add(new EnumParse { Code = 3523107, Description = "ITAQUAQUECETUBA" });
            list.Add(new EnumParse { Code = 3523206, Description = "ITARARE" });
            list.Add(new EnumParse { Code = 3523404, Description = "ITATIBA" });
            list.Add(new EnumParse { Code = 3523909, Description = "ITU" });
            list.Add(new EnumParse { Code = 3524105, Description = "ITUVERAVA" });
            list.Add(new EnumParse { Code = 3524303, Description = "JABOTICABAL" });
            list.Add(new EnumParse { Code = 3524402, Description = "JACAREI" });
            list.Add(new EnumParse { Code = 3524600, Description = "JACUPIRANGA" });
            list.Add(new EnumParse { Code = 3524709, Description = "JAGUARIUNA" });
            list.Add(new EnumParse { Code = 3524808, Description = "JALES" });
            list.Add(new EnumParse { Code = 3525102, Description = "JARDINOPOLIS" });
            list.Add(new EnumParse { Code = 3525300, Description = "JAU" });
            list.Add(new EnumParse { Code = 3525706, Description = "JOSE BONIFACIO" });
            list.Add(new EnumParse { Code = 3525904, Description = "JUNDIAI" });
            list.Add(new EnumParse { Code = 3526001, Description = "JUNQUEIROPOLIS" });
            list.Add(new EnumParse { Code = 3526100, Description = "JUQUIA" });
            list.Add(new EnumParse { Code = 3526407, Description = "LARANJAL PAULISTA" });
            list.Add(new EnumParse { Code = 3526704, Description = "LEME" });
            list.Add(new EnumParse { Code = 3526803, Description = "LENCOIS PAULISTA" });
            list.Add(new EnumParse { Code = 3526902, Description = "LIMEIRA" });
            list.Add(new EnumParse { Code = 3527108, Description = "LINS" });
            list.Add(new EnumParse { Code = 3527207, Description = "LORENA" });
            list.Add(new EnumParse { Code = 3527405, Description = "LUCELIA" });
            list.Add(new EnumParse { Code = 3528007, Description = "MACATUBA" });
            list.Add(new EnumParse { Code = 3528403, Description = "MAIRINQUE" });
            list.Add(new EnumParse { Code = 3528502, Description = "MAIRIPORA" });
            list.Add(new EnumParse { Code = 3528809, Description = "MARACAI" });
            list.Add(new EnumParse { Code = 3529005, Description = "MARILIA" });
            list.Add(new EnumParse { Code = 3529203, Description = "MARTINOPOLIS" });
            list.Add(new EnumParse { Code = 3529302, Description = "MATAO" });
            list.Add(new EnumParse { Code = 3529401, Description = "MAUA" });
            list.Add(new EnumParse { Code = 3529708, Description = "MIGUELOPOLIS" });
            list.Add(new EnumParse { Code = 3529906, Description = "MIRACATU" });
            list.Add(new EnumParse { Code = 3530102, Description = "MIRANDOPOLIS" });
            list.Add(new EnumParse { Code = 3530201, Description = "MIRANTE DO PARANAPANEMA" });
            list.Add(new EnumParse { Code = 3530300, Description = "MIRASSOL" });
            list.Add(new EnumParse { Code = 3530508, Description = "MOCOCA" });
            list.Add(new EnumParse { Code = 3530706, Description = "MOGI GUACU" });
            list.Add(new EnumParse { Code = 3530805, Description = "MOGI-MIRIM" });
            list.Add(new EnumParse { Code = 3530607, Description = "MOJI DAS CRUZES" });
            list.Add(new EnumParse { Code = 3531100, Description = "MONGAGUA" });
            list.Add(new EnumParse { Code = 3531308, Description = "MONTE ALTO" });
            list.Add(new EnumParse { Code = 3531407, Description = "MONTE APRAZIVEL" });
            list.Add(new EnumParse { Code = 3531506, Description = "MONTE AZUL PAULISTA" });
            list.Add(new EnumParse { Code = 3531803, Description = "MONTE MOR" });
            list.Add(new EnumParse { Code = 3531902, Description = "MORRO AGUDO" });
            list.Add(new EnumParse { Code = 3532603, Description = "NHANDEARA" });
            list.Add(new EnumParse { Code = 3533007, Description = "NOVA GRANADA" });
            list.Add(new EnumParse { Code = 3533403, Description = "NOVA ODESSA" });
            list.Add(new EnumParse { Code = 3533502, Description = "NOVO HORIZONTE" });
            list.Add(new EnumParse { Code = 3533601, Description = "NUPORANGA" });
            list.Add(new EnumParse { Code = 3533908, Description = "OLIMPIA" });
            list.Add(new EnumParse { Code = 3534302, Description = "ORLANDIA" });
            list.Add(new EnumParse { Code = 3534401, Description = "OSASCO" });
            list.Add(new EnumParse { Code = 3534609, Description = "OSVALDO CRUZ" });
            list.Add(new EnumParse { Code = 3534708, Description = "OURINHOS" });
            list.Add(new EnumParse { Code = 3534906, Description = "PACAEMBU" });
            list.Add(new EnumParse { Code = 3535002, Description = "PALESTINA" });
            list.Add(new EnumParse { Code = 3535200, Description = "PALMEIRA D OESTE" });
            list.Add(new EnumParse { Code = 3535309, Description = "PALMITAL" });
            list.Add(new EnumParse { Code = 3535408, Description = "PANORAMA" });
            list.Add(new EnumParse { Code = 3535507, Description = "PARAGUACU PAULISTA" });
            list.Add(new EnumParse { Code = 3535606, Description = "PARAIBUNA" });
            list.Add(new EnumParse { Code = 3536307, Description = "PATROCINIO PAULISTA" });
            list.Add(new EnumParse { Code = 3536604, Description = "PAULO DE FARIA" });
            list.Add(new EnumParse { Code = 3536703, Description = "PEDERNEIRAS" });
            list.Add(new EnumParse { Code = 3537008, Description = "PEDREGULHO" });
            list.Add(new EnumParse { Code = 3537107, Description = "PEDREIRA" });
            list.Add(new EnumParse { Code = 3537305, Description = "PENAPOLIS" });
            list.Add(new EnumParse { Code = 3537404, Description = "PEREIRA BARRETO" });
            list.Add(new EnumParse { Code = 3537602, Description = "PERUIBE" });
            list.Add(new EnumParse { Code = 3537800, Description = "PIEDADE" });
            list.Add(new EnumParse { Code = 3537909, Description = "PILAR DO SUL" });
            list.Add(new EnumParse { Code = 3538006, Description = "PINDAMONHANGABA" });
            list.Add(new EnumParse { Code = 3538600, Description = "PIRACAIA" });
            list.Add(new EnumParse { Code = 3538709, Description = "PIRACICABA" });
            list.Add(new EnumParse { Code = 3538808, Description = "PIRAJU" });
            list.Add(new EnumParse { Code = 3538907, Description = "PIRAJUI" });
            list.Add(new EnumParse { Code = 3539202, Description = "PIRAPOZINHO" });
            list.Add(new EnumParse { Code = 3539301, Description = "PIRASSUNUNGA" });
            list.Add(new EnumParse { Code = 3539400, Description = "PIRATININGA" });
            list.Add(new EnumParse { Code = 3539509, Description = "PITANGUEIRAS" });
            list.Add(new EnumParse { Code = 3539806, Description = "POA" });
            list.Add(new EnumParse { Code = 3540002, Description = "POMPEIA" });
            list.Add(new EnumParse { Code = 3540200, Description = "PONTAL" });
            list.Add(new EnumParse { Code = 3540507, Description = "PORANGABA" });
            list.Add(new EnumParse { Code = 3540606, Description = "PORTO FELIZ" });
            list.Add(new EnumParse { Code = 3540705, Description = "PORTO FERREIRA" });
            list.Add(new EnumParse { Code = 3540804, Description = "POTIRENDABA" });
            list.Add(new EnumParse { Code = 3541000, Description = "PRAIA GRANDE" });
            list.Add(new EnumParse { Code = 3541208, Description = "PRESIDENTE BERNARDES" });
            list.Add(new EnumParse { Code = 3541307, Description = "PRESIDENTE EPITACIO" });
            list.Add(new EnumParse { Code = 3541406, Description = "PRESIDENTE PRUDENTE" });
            list.Add(new EnumParse { Code = 3541505, Description = "PRESIDENTE VENCESLAU" });
            list.Add(new EnumParse { Code = 3541604, Description = "PROMISSAO" });
            list.Add(new EnumParse { Code = 3541703, Description = "QUATA" });
            list.Add(new EnumParse { Code = 3541901, Description = "QUELUZ" });
            list.Add(new EnumParse { Code = 3542206, Description = "RANCHARIA" });
            list.Add(new EnumParse { Code = 3542404, Description = "REGENTE FEIJO" });
            list.Add(new EnumParse { Code = 3542602, Description = "REGISTRO" });
            list.Add(new EnumParse { Code = 3542909, Description = "RIBEIRAO BONITO" });
            list.Add(new EnumParse { Code = 3543303, Description = "RIBEIRAO PIRES" });
            list.Add(new EnumParse { Code = 3543402, Description = "RIBEIRAO PRETO" });
            list.Add(new EnumParse { Code = 3543907, Description = "RIO CLARO" });
            list.Add(new EnumParse { Code = 3544251, Description = "ROSANA" });
            list.Add(new EnumParse { Code = 3545209, Description = "SALTO" });
            list.Add(new EnumParse { Code = 3545605, Description = "SANTA ADELIA" });
            list.Add(new EnumParse { Code = 3545803, Description = "SANTA BARBARA D OESTE" });
            list.Add(new EnumParse { Code = 3546009, Description = "SANTA BRANCA" });
            list.Add(new EnumParse { Code = 3546306, Description = "SANTA CRUZ DAS PALMEIRAS" });
            list.Add(new EnumParse { Code = 3546405, Description = "SANTA CRUZ DO RIO PARDO" });
            list.Add(new EnumParse { Code = 3546603, Description = "SANTA FE DO SUL" });
            list.Add(new EnumParse { Code = 3546801, Description = "SANTA ISABEL" });
            list.Add(new EnumParse { Code = 3547502, Description = "SANTA RITA DO PASSA QUATRO" });
            list.Add(new EnumParse { Code = 3547601, Description = "SANTA ROSA DE VITERBO" });
            list.Add(new EnumParse { Code = 3547304, Description = "SANTANA DE PARNAIBA" });
            list.Add(new EnumParse { Code = 3547700, Description = "SANTO ANASTACIO" });
            list.Add(new EnumParse { Code = 3547809, Description = "SANTO ANDRE" });
            list.Add(new EnumParse { Code = 3548500, Description = "SANTOS" });
            list.Add(new EnumParse { Code = 3548609, Description = "SAO BENTO DO SAPUCAI" });
            list.Add(new EnumParse { Code = 3548708, Description = "SAO BERNARDO DO CAMPO" });
            list.Add(new EnumParse { Code = 3548807, Description = "SAO CAETANO DO SUL" });
            list.Add(new EnumParse { Code = 3548906, Description = "SAO CARLOS" });
            list.Add(new EnumParse { Code = 3549102, Description = "SAO JOAO DA BOA VISTA" });
            list.Add(new EnumParse { Code = 3549409, Description = "SAO JOAQUIM DA BARRA" });
            list.Add(new EnumParse { Code = 3549706, Description = "SAO JOSE DO RIO PARDO" });
            list.Add(new EnumParse { Code = 3549805, Description = "SAO JOSE DO RIO PRETO" });
            list.Add(new EnumParse { Code = 3549904, Description = "SAO JOSE DOS CAMPOS" });
            list.Add(new EnumParse { Code = 3550001, Description = "SAO LUIS DO PARAITINGA" });
            list.Add(new EnumParse { Code = 3550100, Description = "SAO MANUEL" });
            list.Add(new EnumParse { Code = 3550209, Description = "SAO MIGUEL ARCANJO" });
            list.Add(new EnumParse { Code = 3550407, Description = "SAO PEDRO" });
            list.Add(new EnumParse { Code = 3550605, Description = "SAO ROQUE" });
            list.Add(new EnumParse { Code = 3550704, Description = "SAO SEBASTIAO" });
            list.Add(new EnumParse { Code = 3550902, Description = "SAO SIMAO" });
            list.Add(new EnumParse { Code = 3551009, Description = "SAO VICENTE" });
            list.Add(new EnumParse { Code = 3551603, Description = "SERRA NEGRA" });
            list.Add(new EnumParse { Code = 3551504, Description = "SERRANA" });
            list.Add(new EnumParse { Code = 3553282, Description = "SERTAOZINHO" });
            list.Add(new EnumParse { Code = 3552106, Description = "SOCORRO" });
            list.Add(new EnumParse { Code = 3552205, Description = "SOROCABA" });
            list.Add(new EnumParse { Code = 3552403, Description = "SUMARE" });
            list.Add(new EnumParse { Code = 3552502, Description = "SUZANO" });
            list.Add(new EnumParse { Code = 3552809, Description = "TABOAO DA SERRA" });
            list.Add(new EnumParse { Code = 3553302, Description = "TAMBAU" });
            list.Add(new EnumParse { Code = 3553401, Description = "TANABI" });
            list.Add(new EnumParse { Code = 3553708, Description = "TAQUARITINGA" });
            list.Add(new EnumParse { Code = 3553807, Description = "TAQUARITUBA" });
            list.Add(new EnumParse { Code = 3554003, Description = "TATUI" });
            list.Add(new EnumParse { Code = 3554102, Description = "TAUBATE" });
            list.Add(new EnumParse { Code = 3554300, Description = "TEODORO SAMPAIO" });
            list.Add(new EnumParse { Code = 3554508, Description = "TIETE" });
            list.Add(new EnumParse { Code = 3554805, Description = "TREMEMBE" });
            list.Add(new EnumParse { Code = 3555000, Description = "TUPA" });
            list.Add(new EnumParse { Code = 3555109, Description = "TUPI PAULISTA" });
            list.Add(new EnumParse { Code = 3555406, Description = "UBATUBA" });
            list.Add(new EnumParse { Code = 3555802, Description = "URANIA" });
            list.Add(new EnumParse { Code = 3556008, Description = "URUPES" });
            list.Add(new EnumParse { Code = 3556206, Description = "VALINHOS" });
            list.Add(new EnumParse { Code = 3556305, Description = "VALPARAISO" });
            list.Add(new EnumParse { Code = 3556404, Description = "VARGEM GRANDE DO SUL" });
            list.Add(new EnumParse { Code = 3556503, Description = "VARZEA PAULISTA" });
            list.Add(new EnumParse { Code = 3556701, Description = "VINHEDO" });
            list.Add(new EnumParse { Code = 3556800, Description = "VIRADOURO" });
            list.Add(new EnumParse { Code = 3557006, Description = "VOTORANTIM" });
            list.Add(new EnumParse { Code = 3557105, Description = "VOTUPORANGA" });
        }

        public List<EnumParse> GetMapped()
        {
            return list;
        }

        public string GetText(int code)
        {
            return list.FirstOrDefault(x => x.Code == code).Description;
        }
    }
}
