using Com.ByteAnalysis.IFacilita.LigthOwnership.Model;
using System.Collections.Generic;
using System.Linq;

namespace Com.ByteAnalysis.IFacilita.LigthOwnership.Service
{
    public class EnumCountryType
    {
        List<EnumParse> list = new List<EnumParse>();
        public EnumCountryType()
        {
            list = new List<EnumParse>();
            list.Add(new EnumParse { Code = "AD", Description = "Andorra" });
            list.Add(new EnumParse { Code = "AE", Description = "EmirÁrabUnids." });
            list.Add(new EnumParse { Code = "AF", Description = "Afeganistão" });
            list.Add(new EnumParse { Code = "AG", Description = "Antígua/Barbuda" });
            list.Add(new EnumParse { Code = "AI", Description = "Anguilla" });
            list.Add(new EnumParse { Code = "AL", Description = "Albânia" });
            list.Add(new EnumParse { Code = "AM", Description = "Armênia" });
            list.Add(new EnumParse { Code = "AN", Description = "AntilhasHoland." });
            list.Add(new EnumParse { Code = "AO", Description = "Angola" });
            list.Add(new EnumParse { Code = "AQ", Description = "Antártica" });
            list.Add(new EnumParse { Code = "AR", Description = "Argentina" });
            list.Add(new EnumParse { Code = "AS", Description = "Samoa Americana" });
            list.Add(new EnumParse { Code = "AT", Description = "Áustria" });
            list.Add(new EnumParse { Code = "AU", Description = "Austrália" });
            list.Add(new EnumParse { Code = "AW", Description = "Aruba" });
            list.Add(new EnumParse { Code = "AZ", Description = "Azerbaijão" });
            list.Add(new EnumParse { Code = "BA", Description = "Bósnia-Herzeg." });
            list.Add(new EnumParse { Code = "BB", Description = "Barbados" });
            list.Add(new EnumParse { Code = "BD", Description = "Bangladesh" });
            list.Add(new EnumParse { Code = "BE", Description = "Bélgica" });
            list.Add(new EnumParse { Code = "BF", Description = "Burquina Faso" });
            list.Add(new EnumParse { Code = "BG", Description = "Bulgária" });
            list.Add(new EnumParse { Code = "BH", Description = "Barein" });
            list.Add(new EnumParse { Code = "BI", Description = "Burundi" });
            list.Add(new EnumParse { Code = "BJ", Description = "Benin" });
            list.Add(new EnumParse { Code = "BL", Description = "Saint-Barthélem" });
            list.Add(new EnumParse { Code = "BM", Description = "Bermudas" });
            list.Add(new EnumParse { Code = "BN", Description = "Brunei" });
            list.Add(new EnumParse { Code = "BO", Description = "Bolívia" });
            list.Add(new EnumParse { Code = "BR", Description = "Brasil" });
            list.Add(new EnumParse { Code = "BS", Description = "Bahamas" });
            list.Add(new EnumParse { Code = "BT", Description = "Butão" });
            list.Add(new EnumParse { Code = "BV", Description = "Ilhas Bouvet" });
            list.Add(new EnumParse { Code = "BW", Description = "Botsuana" });
            list.Add(new EnumParse { Code = "BY", Description = "Bielo-Rússia" });
            list.Add(new EnumParse { Code = "BZ", Description = "Belize" });
            list.Add(new EnumParse { Code = "CA", Description = "Canadá" });
            list.Add(new EnumParse { Code = "CC", Description = "Ilhas Coco" });
            list.Add(new EnumParse { Code = "CD", Description = "República Congo" });
            list.Add(new EnumParse { Code = "CF", Description = "RepCentroAfric." });
            list.Add(new EnumParse { Code = "CG", Description = "Congo" });
            list.Add(new EnumParse { Code = "CH", Description = "Suíça" });
            list.Add(new EnumParse { Code = "CI", Description = "Costa do Marfim" });
            list.Add(new EnumParse { Code = "CK", Description = "Ilha Cook" });
            list.Add(new EnumParse { Code = "CL", Description = "Chile" });
            list.Add(new EnumParse { Code = "CM", Description = "Camarões" });
            list.Add(new EnumParse { Code = "CN", Description = "China" });
            list.Add(new EnumParse { Code = "CO", Description = "Colômbia" });
            list.Add(new EnumParse { Code = "CR", Description = "Costa Rica" });
            list.Add(new EnumParse { Code = "CS", Description = "Sérvia/Montngro" });
            list.Add(new EnumParse { Code = "CU", Description = "Cuba" });
            list.Add(new EnumParse { Code = "CV", Description = "Cabo Verde" });
            list.Add(new EnumParse { Code = "CX", Description = "Ilha Christmas" });
            list.Add(new EnumParse { Code = "CY", Description = "Chipre" });
            list.Add(new EnumParse { Code = "CZ", Description = "RepúblicaTcheca" });
            list.Add(new EnumParse { Code = "DE", Description = "Alemanha" });
            list.Add(new EnumParse { Code = "DJ", Description = "Djibuti" });
            list.Add(new EnumParse { Code = "DK", Description = "Dinamarca" });
            list.Add(new EnumParse { Code = "DM", Description = "Dominica" });
            list.Add(new EnumParse { Code = "DO", Description = "Rep.Dominicana" });
            list.Add(new EnumParse { Code = "DZ", Description = "Argélia" });
            list.Add(new EnumParse { Code = "EC", Description = "Equador" });
            list.Add(new EnumParse { Code = "EE", Description = "Estônia" });
            list.Add(new EnumParse { Code = "EG", Description = "Egito" });
            list.Add(new EnumParse { Code = "EH", Description = "Saara Ocidental" });
            list.Add(new EnumParse { Code = "ER", Description = "Eritréia" });
            list.Add(new EnumParse { Code = "ES", Description = "Espanha" });
            list.Add(new EnumParse { Code = "ET", Description = "Etiópia" });
            list.Add(new EnumParse { Code = "EU", Description = "União Européia" });
            list.Add(new EnumParse { Code = "FI", Description = "Finlândia" });
            list.Add(new EnumParse { Code = "FJ", Description = "Fiji" });
            list.Add(new EnumParse { Code = "FK", Description = "Ilhas Malvinas" });
            list.Add(new EnumParse { Code = "FM", Description = "Micronésia" });
            list.Add(new EnumParse { Code = "FO", Description = "Ilhas Faroé" });
            list.Add(new EnumParse { Code = "FR", Description = "França" });
            list.Add(new EnumParse { Code = "GA", Description = "Gabão" });
            list.Add(new EnumParse { Code = "GB", Description = "Reino Unido" });
            list.Add(new EnumParse { Code = "GD", Description = "Granada" });
            list.Add(new EnumParse { Code = "GE", Description = "Geórgia" });
            list.Add(new EnumParse { Code = "GF", Description = "Guiana Francesa" });
            list.Add(new EnumParse { Code = "GH", Description = "Gana" });
            list.Add(new EnumParse { Code = "GI", Description = "Gibraltar" });
            list.Add(new EnumParse { Code = "GL", Description = "Groenlândia" });
            list.Add(new EnumParse { Code = "GM", Description = "Gâmbia" });
            list.Add(new EnumParse { Code = "GN", Description = "Guiné" });
            list.Add(new EnumParse { Code = "GP", Description = "Guadalupe" });
            list.Add(new EnumParse { Code = "GQ", Description = "Guiné Equator." });
            list.Add(new EnumParse { Code = "GR", Description = "Grécia" });
            list.Add(new EnumParse { Code = "GS", Description = "Ilhas Sandwich" });
            list.Add(new EnumParse { Code = "GT", Description = "Guatemala" });
            list.Add(new EnumParse { Code = "GU", Description = "Guam" });
            list.Add(new EnumParse { Code = "GW", Description = "Guiné Bissau" });
            list.Add(new EnumParse { Code = "GY", Description = "Guiana" });
            list.Add(new EnumParse { Code = "HK", Description = "Hong Kong" });
            list.Add(new EnumParse { Code = "HM", Description = "Heard/Ilh.McDon" });
            list.Add(new EnumParse { Code = "HN", Description = "Honduras" });
            list.Add(new EnumParse { Code = "HR", Description = "Croácia" });
            list.Add(new EnumParse { Code = "HT", Description = "Haiti" });
            list.Add(new EnumParse { Code = "HU", Description = "Hungria" });
            list.Add(new EnumParse { Code = "ID", Description = "Indonésia" });
            list.Add(new EnumParse { Code = "IE", Description = "Irlanda" });
            list.Add(new EnumParse { Code = "IL", Description = "Israel" });
            list.Add(new EnumParse { Code = "IN", Description = "Índia" });
            list.Add(new EnumParse { Code = "IO", Description = "Terr.Brit.Oc.In" });
            list.Add(new EnumParse { Code = "IQ", Description = "Iraque" });
            list.Add(new EnumParse { Code = "IR", Description = "Irã" });
            list.Add(new EnumParse { Code = "IS", Description = "Islândia" });
            list.Add(new EnumParse { Code = "IT", Description = "Itália" });
            list.Add(new EnumParse { Code = "JM", Description = "Jamaica" });
            list.Add(new EnumParse { Code = "JO", Description = "Jordânia" });
            list.Add(new EnumParse { Code = "JP", Description = "Japão" });
            list.Add(new EnumParse { Code = "KE", Description = "Quênia" });
            list.Add(new EnumParse { Code = "KG", Description = "Quirguistão" });
            list.Add(new EnumParse { Code = "KH", Description = "Camboja" });
            list.Add(new EnumParse { Code = "KI", Description = "Kiribati" });
            list.Add(new EnumParse { Code = "KM", Description = "Comores" });
            list.Add(new EnumParse { Code = "KN", Description = "S.Crist.e Névis" });
            list.Add(new EnumParse { Code = "KP", Description = "Coréia do Norte" });
            list.Add(new EnumParse { Code = "KR", Description = "Coréia do Sul" });
            list.Add(new EnumParse { Code = "KW", Description = "Kuaite" });
            list.Add(new EnumParse { Code = "KY", Description = "Ilhas Cayman" });
            list.Add(new EnumParse { Code = "KZ", Description = "Cazaquistão" });
            list.Add(new EnumParse { Code = "LA", Description = "Laos" });
            list.Add(new EnumParse { Code = "LB", Description = "Líbano" });
            list.Add(new EnumParse { Code = "LC", Description = "Santa Lúcia" });
            list.Add(new EnumParse { Code = "LI", Description = "Liechtenstein" });
            list.Add(new EnumParse { Code = "LK", Description = "Sri Lanka" });
            list.Add(new EnumParse { Code = "LR", Description = "Libéria" });
            list.Add(new EnumParse { Code = "LS", Description = "Lesoto" });
            list.Add(new EnumParse { Code = "LT", Description = "Lituânia" });
            list.Add(new EnumParse { Code = "LU", Description = "Luxemburgo" });
            list.Add(new EnumParse { Code = "LV", Description = "Letônia" });
            list.Add(new EnumParse { Code = "LY", Description = "Líbia" });
            list.Add(new EnumParse { Code = "MA", Description = "Marrocos" });
            list.Add(new EnumParse { Code = "MC", Description = "Mônaco" });
            list.Add(new EnumParse { Code = "MD", Description = "Moldova" });
            list.Add(new EnumParse { Code = "MG", Description = "Madagascar" });
            list.Add(new EnumParse { Code = "MH", Description = "Ilhas Marshall" });
            list.Add(new EnumParse { Code = "MK", Description = "Macedônia" });
            list.Add(new EnumParse { Code = "ML", Description = "Mali" });
            list.Add(new EnumParse { Code = "MM", Description = "Myanmar" });
            list.Add(new EnumParse { Code = "MN", Description = "Mongólia" });
            list.Add(new EnumParse { Code = "MO", Description = "Macau" });
            list.Add(new EnumParse { Code = "MP", Description = "I.Marianas Nrt." });
            list.Add(new EnumParse { Code = "MQ", Description = "Martinica" });
            list.Add(new EnumParse { Code = "MR", Description = "Mauritânia" });
            list.Add(new EnumParse { Code = "MS", Description = "Montserrat" });
            list.Add(new EnumParse { Code = "MT", Description = "Malta" });
            list.Add(new EnumParse { Code = "MU", Description = "Maurício" });
            list.Add(new EnumParse { Code = "MV", Description = "Maldivas" });
            list.Add(new EnumParse { Code = "MW", Description = "Maláwi" });
            list.Add(new EnumParse { Code = "MX", Description = "México" });
            list.Add(new EnumParse { Code = "MY", Description = "Malásia" });
            list.Add(new EnumParse { Code = "MZ", Description = "Moçambique" });
            list.Add(new EnumParse { Code = "NA", Description = "Namíbia" });
            list.Add(new EnumParse { Code = "NC", Description = "Nova Caledônia" });
            list.Add(new EnumParse { Code = "NE", Description = "Níger" });
            list.Add(new EnumParse { Code = "NF", Description = "Ilha Norfolk" });
            list.Add(new EnumParse { Code = "NG", Description = "Nigéria" });
            list.Add(new EnumParse { Code = "NI", Description = "Nicarágua" });
            list.Add(new EnumParse { Code = "NL", Description = "Países Baixos" });
            list.Add(new EnumParse { Code = "NO", Description = "Noruega" });
            list.Add(new EnumParse { Code = "NP", Description = "Nepal" });
            list.Add(new EnumParse { Code = "NR", Description = "Nauru" });
            list.Add(new EnumParse { Code = "NU", Description = "Niue" });
            list.Add(new EnumParse { Code = "NZ", Description = "Nova Zelândia" });
            list.Add(new EnumParse { Code = "OM", Description = "Omã" });
            list.Add(new EnumParse { Code = "OR", Description = "Alaranjado" });
            list.Add(new EnumParse { Code = "PA", Description = "Panamá" });
            list.Add(new EnumParse { Code = "PE", Description = "Peru" });
            list.Add(new EnumParse { Code = "PF", Description = "PolinésiaFranc." });
            list.Add(new EnumParse { Code = "PG", Description = "Papua NovaGuiné" });
            list.Add(new EnumParse { Code = "PH", Description = "Filipinas" });
            list.Add(new EnumParse { Code = "PK", Description = "Paquistão" });
            list.Add(new EnumParse { Code = "PL", Description = "Polônia" });
            list.Add(new EnumParse { Code = "PM", Description = "S.Pedro,Miquel." });
            list.Add(new EnumParse { Code = "PN", Description = "Ilha Pitcairn" });
            list.Add(new EnumParse { Code = "PR", Description = "Porto Rico" });
            list.Add(new EnumParse { Code = "PS", Description = "Palestina" });
            list.Add(new EnumParse { Code = "PT", Description = "Portugal" });
            list.Add(new EnumParse { Code = "PW", Description = "Palau" });
            list.Add(new EnumParse { Code = "PY", Description = "Paraguai" });
            list.Add(new EnumParse { Code = "QA", Description = "Catar" });
            list.Add(new EnumParse { Code = "RE", Description = "Reunião" });
            list.Add(new EnumParse { Code = "RO", Description = "Romênia" });
            list.Add(new EnumParse { Code = "RU", Description = "Federação Russa" });
            list.Add(new EnumParse { Code = "RW", Description = "Ruanda" });
            list.Add(new EnumParse { Code = "SA", Description = "Arábia Saudita" });
            list.Add(new EnumParse { Code = "SB", Description = "Ilhas Salomão" });
            list.Add(new EnumParse { Code = "SC", Description = "Seicheles" });
            list.Add(new EnumParse { Code = "SD", Description = "Sudão" });
            list.Add(new EnumParse { Code = "SE", Description = "Suécia" });
            list.Add(new EnumParse { Code = "SG", Description = "Cingapura" });
            list.Add(new EnumParse { Code = "SH", Description = "Santa Helena" });
            list.Add(new EnumParse { Code = "SI", Description = "Eslovênia" });
            list.Add(new EnumParse { Code = "SJ", Description = "Svalbard" });
            list.Add(new EnumParse { Code = "SK", Description = "Eslováquia" });
            list.Add(new EnumParse { Code = "SL", Description = "Serra Leoa" });
            list.Add(new EnumParse { Code = "SM", Description = "San Marino" });
            list.Add(new EnumParse { Code = "SN", Description = "Senegal" });
            list.Add(new EnumParse { Code = "SO", Description = "Somália" });
            list.Add(new EnumParse { Code = "SR", Description = "Suriname" });
            list.Add(new EnumParse { Code = "ST", Description = "S.Tomé,Príncipe" });
            list.Add(new EnumParse { Code = "SV", Description = "El Salvador" });
            list.Add(new EnumParse { Code = "SY", Description = "Síria" });
            list.Add(new EnumParse { Code = "SZ", Description = "Suazilandia" });
            list.Add(new EnumParse { Code = "TC", Description = "I.Turcas,Caicos" });
            list.Add(new EnumParse { Code = "TD", Description = "Chade" });
            list.Add(new EnumParse { Code = "TF", Description = "TerMerid.França" });
            list.Add(new EnumParse { Code = "TG", Description = "Togo" });
            list.Add(new EnumParse { Code = "TH", Description = "Tailândia" });
            list.Add(new EnumParse { Code = "TJ", Description = "Tadjiquistão" });
            list.Add(new EnumParse { Code = "TK", Description = "Ilhas Toquelau" });
            list.Add(new EnumParse { Code = "TL", Description = "Timor Leste" });
            list.Add(new EnumParse { Code = "TM", Description = "Turcomenistão" });
            list.Add(new EnumParse { Code = "TN", Description = "Tunísia" });
            list.Add(new EnumParse { Code = "TO", Description = "Tonga" });
            list.Add(new EnumParse { Code = "TP", Description = "Timor Leste" });
            list.Add(new EnumParse { Code = "TR", Description = "Turquia" });
            list.Add(new EnumParse { Code = "TT", Description = "Trinidad,Tobago" });
            list.Add(new EnumParse { Code = "TV", Description = "Tuvalu" });
            list.Add(new EnumParse { Code = "TW", Description = "Taiwan" });
            list.Add(new EnumParse { Code = "TZ", Description = "Tanzânia" });
            list.Add(new EnumParse { Code = "UA", Description = "Ucrânia" });
            list.Add(new EnumParse { Code = "UG", Description = "Uganda" });
            list.Add(new EnumParse { Code = "UM", Description = "I.Menores EUA" });
            list.Add(new EnumParse { Code = "US", Description = "EUA" });
            list.Add(new EnumParse { Code = "UY", Description = "Uruguai" });
            list.Add(new EnumParse { Code = "UZ", Description = "Uzbequistão" });
            list.Add(new EnumParse { Code = "VA", Description = "Vaticano" });
            list.Add(new EnumParse { Code = "VC", Description = "São Vicente" });
            list.Add(new EnumParse { Code = "VE", Description = "Venezuela" });
            list.Add(new EnumParse { Code = "VG", Description = "I.Virgens Brit." });
            list.Add(new EnumParse { Code = "VI", Description = "I.Virgens Amer." });
            list.Add(new EnumParse { Code = "VN", Description = "Vietnã" });
            list.Add(new EnumParse { Code = "VU", Description = "Vanuato" });
            list.Add(new EnumParse { Code = "WF", Description = "Wallis,Futuna" });
            list.Add(new EnumParse { Code = "WS", Description = "Samoa Ocidental" });
            list.Add(new EnumParse { Code = "YE", Description = "Iêmen" });
            list.Add(new EnumParse { Code = "YT", Description = "Mayotte" });
            list.Add(new EnumParse { Code = "ZA", Description = "África do Sul" });
            list.Add(new EnumParse { Code = "ZM", Description = "Zâmbia" });
            list.Add(new EnumParse { Code = "ZW", Description = "Zimbábue" });
        }

        public List<EnumParse> GetMapped()
        {
            return list;
        }

        public string GetText(string code)
        {
            return list.FirstOrDefault(x => x.Code == code).Description;
        }
    }
}
